### ISSUE TITLE
Add support for loading components from subdirectories 

### ISSUE THREAD

**Issue by JamesHagerman** [flowbased/fbp-manifest#1]
In larger component libraries, separating components into subdirectories of related code would be a wonderfully helpful feature.

This ticket is being made in response to @bergie's reply on this `noflo` issue: https://github.com/noflo/noflo/issues/425

**Comment by JamesHagerman** [comment]
@bergie Is there a quick fix for this?

**Comment by bergie** [comment]
@JamesHagerman can you give the changeset in #2 a spin? Should fix the issue

**Comment by JamesHagerman** [comment]
Hey @bergie, I'll try it this week some time if I get a spare moment!

Thank you so much for the help! I'll let you know how it goes!

**Comment by JamesHagerman** [comment]
@bergie Today I FINALLY had a chance to test this. It seems to work very well!

The only change I had to make was to add an extra layer of directory traversal to any require() statements in my components to account for the extra layer of directory structure.

Thank you SO much for your patience! It's been a busy month and this makes things a LOT easier to manage. Thank you!

**Comment by JamesHagerman** [comment]
Ah, one more note. The components are still namespaced the same as they would be if they were not in subdirectories.

For example, if we have an `app/components/myLibrary/term.js` and a `app/components/myOtherLibrary/term.js` they will both try to be namespaced as `app/term`.

So that might be something to ponder about fixing at some point in the future.

**Comment by trustmaster** [comment]
Any ideas of a release schedule for this feature? Documentation on how to use it would be very appreciated too.

**Comment by linonetwo** [comment]
How to use this tool?
